[{
  "firstName":"yathendra",
  "lastName":"alluru",
  "gender":"male",
  "age":29,
  "ph":"9999999999",
  "address":"13-152,kasipeta,venkatagiri."
},{
  "firstName":"pravana",
  "lastName":"alluru",
  "gender":"male",
  "age":39,
  "ph":"8888888888",
  "address":"13-151,kasipeta,venkatagiri."
},{
  "firstName":"raghava",
  "lastName":"alluru",
  "gender":"male",
  "age":27,
  "ph":"7777777777",
  "address":"2-248,kasipeta,venkatagiri."
}
]