#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    firstName:
    lastName:
    gender:
      enum:
        - male
        - female
    age:
      type: number
    ph:
    address:
    